OCAMLMAKEFILE=../OCamlMakefile

SOURCES=fusexmp.ml
RESULT=fusexmp
CLIBS=fuse camlidl
LIBS=bigarray Fuse
THREADS=threads
TRASH=*~ \\\#*
CFLAGS=-D_FILE_OFFSET_BITS=64 -I. -pthread

LIBDIRS=$(OCAMLLIBPATH)/site-packages/ocamlfuse
INCDIRS=$(LIBDIRS)

target: native-code

-include $(OCAMLMAKEFILE)
